server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  #静态资源处理
  resources:
    #启动默认静态资源处理，默认启动
    add-mappings: true
    cache:
      cachecontrol:
        #缓存响应时间，单位秒
        max-age: 3600
    chain:
      #资源配链启动缓存，默认启动
      cache: true
      #启动资源链，默认禁用
      enabled: true
      #启用压缩资源（gzip，brotil）解析，默认禁用
      compressed: true
      #启用h5应用缓存，默认禁用
      html-application-cache: true
    static-locations: classpath:/template/
  #数据源配置
  data:
    mongodb:
      # 主机地址x
      host: localhost
      # 数据库
      database: videoSubtitle
      # 默认端口是27017
      port: 27017

#      uri:mongodb://localhost:27017/videoSubtitle


#设置上传文件大小，默认是1M
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB